---
#
# mqtt-relay configuration
#
# Pay attention to the comments below and
# make changes appropriate for your own requirements
# 
# Params for the source broker
# This example is for an insecure broker running locally
# Please surround parameters with "#" or ":" with quotes,
# as those characters are a part of the YAML syntax
brokerInUrl: "mqtt://localhost:1883"
brokerInOptions:
  username:
  password:

# topicIn is mandatory. It can be with or without MQTT wildcards
# It needs to be surrounded by quotes if the "#" wildcard is included
# An array of topics will be subscribed in sequence
topicIn: 
  - "whatever/#"
  - "what/else/do/you/have/in/mind#"

####################################
# Params for the destfination broker
# This example is for a remote broker secured with SSL/TLS and authentication
brokerOutUrl: "mqtts://broker.example.com:8883"
brokerOutOptions:
  username: your_username
  password: your_very_secret_password

# topicOutPrefix can be blank or whatever with or without a trailing "/". 
# This will be prepended to outgoing topic
topicOutPrefix: relay/

debug: true

